### ISSUE TITLE
Add a command for checking for updates

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#162]
As explained in [the docs](https://fman.io/docs/automatic-updates), automatic updates are currently "external" to fman. In other words, it's not possible to force-update from within fman, or see the current update status (eg. whether an update is being downloaded / installed). The goal of this issue is to make this possible.

**Comment by CameronBanga** [comment]
Following this one, had some issues with auto-update on Mac today (trying to grab the sort update). Tried quitting/reopening, but not sure, couldn't get it to hold.

Ended up just re-downloading from website, and that worked.

**Comment by mherrmann** [comment]
Yes. I'm afraid the auto-update mechanism was broken in fman for Mac 0.8.2 and 0.8.3. Sorry for the inconvenience. It's fixed in 0.8.4.

**Comment by CameronBanga** [comment]
Perfect, well then nevermind! I should be good now, on 0.8.4.

**Comment by mherrmann** [comment]
Yes, hopefully :+1:

**Comment by raguay** [comment]
I just manually updated. First launch I recieved this message:

Could not load folder /-psn_0_144636391

Traceback (most recent call last):
  File "fman/impl/session.py", line 105, in _init_pane
  File "fman/impl/plugins/mother_fs.py", line 56, in is_dir
  File "fman/impl/plugins/mother_fs.py", line 151, in _query_cache
  File "fman/impl/plugins/mother_fs.py", line 147, in _query_cache
  File "fman/impl/plugins/mother_fs.py", line 160, in _query
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/local/__init__.py", line 40, in is_dir
    return S_ISDIR(os.stat(existing_path).st_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/-psn_0_144636391'

exiting and reloading and I did not get it again. Not sure what that is.

**Comment by mherrmann** [comment]
Thanks for the report @raguay. I just fixed this for release 0.8.5.

**Comment by raguay** [comment]
I'm not getting 0.8.5 to install. Do I need to do a manual install for it as well?

**Comment by mherrmann** [comment]
You did leave fman running for a few mins @raguay before restarting?

**Comment by mherrmann** [comment]
I really need to display some feedback about update status.

**Comment by raguay** [comment]
for 10 minutes between five different tries. I figured that should get it if it was going to.

**Comment by mherrmann** [comment]
Yes :( And you're on 0.8.4?

**Comment by raguay** [comment]
Yes. 0.8.4. I'm also back in Thailand with fast fiber internet connection and not using cellar data right now. Therefore, it's not an connectivity issue.

**Comment by mherrmann** [comment]
What do you get when you

1. Start `/Applications/fman.app/Contents/MacOS/fman` from the Terminal
2. Leave running for 5 minutes.
3. Close.
5. Start `/Applications/fman.app/Contents/MacOS/fman` from the Terminal again.

I don't understand (yet) why it doesn't work and am hoping the above will give some output explaining why. fman successfully updated from 0.8.4 to 0.8.5 on my system.

**Comment by mherrmann** [comment]
(As always, sorry for the inconvenience.)

**Comment by mherrmann** [comment]
(As always, sorry for the inconvenience.)

**Comment by mherrmann** [comment]
Ah, and! The update check only starts once you clicked away the nag screen. I presume you don't get the nag screen because you have a license @raguay, but just in case.

**Comment by macosxguru** [comment]
To murky the waters a bit, it worked fine on my system. Updated fine here.

macosxguru

**Comment by raguay** [comment]
Okay. It just worked for me with the new update to the macOS. I didn't get to try it your way above. The VPN was off as well. Maybe the VPN messed it up this time. Not sure.

Yes, I've never seen the nag screen.

**Comment by mherrmann** [comment]
Okay, I'm glad it at least updated now. But it seems to be a constant pain point. I today looked into adding some visual feedback about update progress (at least something along the lines of a status message "Downloading update" or similar). Unfortunately, it's not as easy as one would hope.
