### ISSUE TITLE
Creating new directory with existing directory name raises exception

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#168]
Create new directory. Create another directory by using name of previously created directory. You'll get ugly exception:
````
Command 'CreateDirectory' raised exception.

Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 90, in _run_in_thread
  File "C:\Users\User\AppData\Local\fman\Versions\0.4.7\Plugins\Core\core\commands.py", line 332, in __call__
    mkdir(dir_path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'D:\\temp\\new'

Would be nice to get an error message "Directory exists" or similar.

**Comment by mherrmann** [comment]
Fixed. Will go live with release 0.4.9.
