### ISSUE TITLE
ImportError: /opt/fman/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found

### ISSUE THREAD

**Issue by p1tt1** [fman-community/fman#182]
* I use the aur package (https://aur.archlinux.org/packages/fman/).
* installed openssl packages:  core/openssl 1.1.0.f-1; extra/openssl-1.0 1.0.2.l-1

```bash
$ /opt/fman/fman
Traceback (most recent call last):
  File "fman/main.py", line 1, in <module>
  File "/home/michael/dev/fman/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "fman/impl/application_context.py", line 18, in <module>
  File "/home/michael/dev/fman/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "fman/impl/signal_.py", line 1, in <module>
  File "/home/michael/dev/fman/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: /opt/fman/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /usr/lib/libQt5Network.so.5)
Failed to execute script main

```

**Comment by mherrmann** [comment]
You're right this is an issue (as I mention in the comment on the AUR page you link to). I will fix this as soon as possible. Unfortunately, my [laptop got stolen](https://fman.io/blog/lost-laptop/) and it will take me a while longer until I'm fully up to speed again. Sorry for the inconvenience.

**Comment by p1tt1** [comment]
thanks

**Comment by mherrmann** [comment]
You're welcome! Thank you for your patience.
