### ISSUE TITLE
Fman doesnt start

### ISSUE THREAD

**Issue by averrin** [fman-community/fman#237]
Fman doesnt start without any prompt.
My system: Arch, **Wayland**, Sway

**Comment by mherrmann** [comment]
Thank you for reporting this. What do you see when you run `/opt/fman/fman` from the command line?

**Comment by averrin** [comment]
```python
Traceback (most recent call last):
  File "fman/main.py", line 1, in <module>
  File "/root/dev/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fman/__init__.py", line 1, in <module>
  File "/root/dev/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fman/clipboard.py", line 2, in <module>
  File "/root/dev/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fman/util/qt.py", line 3, in <module>
  File "/root/dev/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /usr/lib/libGL.so.1: undefined symbol: __GLXGL_CORE_FUNCTIONS
Failed to execute script main
```

**Comment by mannp** [comment]
Getting the exact same error here.

Arch on QubesOS with build from pacaur.

Its been running fine, so not sure if the error occurred with the latest update, if it was done in the last couple of days.

**Comment by mherrmann** [comment]
Do you also get the error with the latest release, 0.7.1? I just tested it on an up-to-date Arch KDE installation and it works fine.

**Comment by mherrmann** [comment]
(The latest release came out today.)

**Comment by mannp** [comment]
Works for me @mherrmann , thanks for the update 👍

**Comment by mherrmann** [comment]
Glad to hear it! Does it work for you too @averrin?

**Comment by mannp** [comment]
Oddly Cmd Shift P doesn't do anything for me now .... ?? Not sure what is happening yet.

**Comment by mherrmann** [comment]
Hm, don't know why. It works for me (as before, on KDE).

**Comment by mherrmann** [comment]
Closing this issue now as the problem with fman not starting on Arch seems to be resolved.
