### ISSUE TITLE
[Bug] Error while installing plugin.

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#257]
A user of my plugin, favorites, encountered this issue:

Command 'InstallPlugin' raised error.

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 270, in _run_in_thread
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/commands.py", line 1165, in __call__
    dest_dir = self._install_plugin(repo.name, zipball_contents)
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/commands.py", line 1199, in _install_plugin
    dir_in_zip, = iterdir(zip_url)
  File "fman/impl/util/__init__.py", line 137, in __next__
  File "fman/impl/util/__init__.py", line 114, in get_next
  File "fman/impl/util/__init__.py", line 118, in _generate_next
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/zip.py", line 46, in iterdir
    for candidate in self._iter_names(zip_path, path_in_zip):
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/zip.py", line 235, in _iter_names
    for file_info in self._iter_infos(zip_path, path_in_zip):
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/zip.py", line 247, in _iter_infos
    raise filenotfounderror(url)
FileNotFoundError: [Errno 2] No such file or directory: 'zip:///var/folders/6r/rf3yfzqd6js8c1p3s7bmz5hc0000gn/T/tmp56w3cx48/plugin.zip/'

Since it is about installing and not running my plugin, I've copied it here. The originator is:  https://github.com/NvL-WEAP

**Comment by mherrmann** [comment]
The same user also reported the same error for one of my plugins ([here](https://github.com/mherrmann/ArrowNavigation/issues/2)). Let's continue the discussion here please @NvL-WEAP, as the error you encountered applies to fman as a whole, not just specific plugins.

**Comment by mherrmann** [comment]
Are you still experiencing this issue @NvL-WEAP?

**Comment by mherrmann** [comment]
Closing this issue as it's unclear whether it still appears.
