### ISSUE TITLE
`FileNotFoundError` when installing a third-party plugin for the first time

### ISSUE THREAD

**Issue by fndari** [fman-community/fman#263]
I tried to install a third-party plugin for the first time via the `Install Plugin` command, and this error message was shown:

```py
Command 'InstallPlugin' raised error.

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 270, in _run_in_thread
  File "/opt/fman/Plugins/Core/core/commands.py", line 1160, in __call__
    dest_dir = self._install_plugin(repo.name, zipball_contents)
  File "/opt/fman/Plugins/Core/core/commands.py", line 1195, in _install_plugin
    copy(join(zip_url, dir_in_zip), dest_dir_url)
  File "fman/fs.py", line 33, in copy
  File "fman/impl/plugins/mother_fs.py", line 113, in copy
  File "/opt/fman/Plugins/Core/core/fs/zip.py", line 90, in copy
    self._extract(zip_path, path_in_zip, dst_path)
  File "/opt/fman/Plugins/Core/core/fs/zip.py", line 194, in _extract
    tmp_dir = self._create_temp_dir_next_to(dst_path)
  File "/opt/fman/Plugins/Core/core/fs/zip.py", line 150, in _create_temp_dir_next_to
    dir=str(PurePosixPath(path).parent), prefix='', suffix='.tmp'
  File "tempfile.py", line 790, in __init__
  File "tempfile.py", line 368, in mkdtemp
FileNotFoundError: [Errno 2] No such file or directory: '/home/[MY USERNAME]/.config/fman/Plugins/Third-party/8rp8dhfq.tmp'
```
Creating the directory manually via `mkdir -p ~/.config/fman/Plugins/Third-party` and installing the plugin again solved this issue.

If relevant: fman version is 0.7.5, operating system is Ubuntu 16.04.3.

**Comment by mherrmann** [comment]
Sorry for the inconvenience and thank you for reporting the bug. I just released fman 0.7.6 which fixes the issue.
