### ISSUE TITLE
errors with ImDisk ramdisk(drive)

### ISSUE THREAD

**Issue by ElnathK** [fman-community/fman#287]
I'm using windows 10 and imdisk toolkit to mount the ramdisk on R. it is no problem that starting fman and browsing the root of R drive. it shows root of R drive and I can open files in the root on fman.
(below are errors. of course, it doesn't occur on internal, external drive (USB 3.0 HDD) and mounted CD/DVD ISO image on windows 10)

1. fman cannot access subfolder of R drive. 
![report2](https://user-images.githubusercontent.com/19336771/34550266-c7f003c6-f152-11e7-99b9-b8473a4a573d.png)

2. if I closed fman that any pane viewed R drive, (next time) fman have started with Traceback message(pane directory also reset to user directory). 
![bugreport](https://user-images.githubusercontent.com/19336771/34550074-39bc6f96-f151-11e7-9e43-6d417373027c.png)

3. If I rename the file on the root, it works. However, a traceback message appears.
![report3](https://user-images.githubusercontent.com/19336771/34550786-ea41cad2-f156-11e7-921d-a28ab909b3ae.png)

**Comment by felubra** [comment]
I'm having the same issue, although the error occurs when I try to access the root of a normal NTFS volume in a normal HDD drive.

Windows 10.0.16299.125.

```
Command 'OpenDirectory' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 270, in _run_in_thread
  File "C:\Users\<user>\AppData\Local\fman\Versions\0.8.2\Plugins\Core\core\commands.py", line 184, in __call__
    self.pane.set_path(url)
  File "fman\__init__.py", line 107, in set_path
  File "fman\impl\widgets.py", line 106, in set_location
  File "fman\impl\model\__init__.py", line 537, in set_location
  File "fman\impl\model\__init__.py", line 179, in set_location
  File "fman\impl\model\__init__.py", line 304, in _load_rows
  File "fman\impl\model\__init__.py", line 344, in _load_row
  File "fman\impl\model\__init__.py", line 344, in <listcomp>
  File "fman\impl\model\__init__.py", line 333, in get
  File "fman\impl\model\__init__.py", line 341, in <lambda>
  File "C:\Users\<user>\AppData\Local\fman\Versions\0.8.2\Plugins\Core\core\fs\columns.py", line 72, in get_sort_value
    return is_dir ^ is_ascending, self._get_mtime(url)
  File "C:\Users\<user>\AppData\Local\fman\Versions\0.8.2\Plugins\Core\core\fs\columns.py", line 74, in _get_mtime
    return self._fs.query(url, 'get_modified_datetime')
  File "fman\fs.py", line 39, in query
  File "fman\impl\plugins\mother_fs.py", line 54, in query
  File "fman\impl\plugins\mother_fs.py", line 151, in _query_cache
  File "fman\impl\plugins\mother_fs.py", line 147, in _query_cache
  File "fman\impl\plugins\mother_fs.py", line 161, in _query
  File "C:\Users\<user>\AppData\Local\fman\Versions\0.8.2\Plugins\Core\core\fs\local\__init__.py", line 39, in get_modified_datetime
    return datetime.fromtimestamp(getmtime(path))
OSError: [Errno 22] Invalid argument

```

**Comment by felubra** [comment]
OK, so I found the possible cause (for my case): in my system there is a file that does not have a (valid) modification date, so fman throws this exception and breaks the operation:
![image](https://user-images.githubusercontent.com/25326257/34637590-b6968128-f2a0-11e7-85bf-18f7d6e35c7b.png)
![image](https://user-images.githubusercontent.com/25326257/34637605-d31cbb0a-f2a0-11e7-8d15-5c36898b3d1a.png)
Removing the problematic file solved this situation.

**Comment by mherrmann** [comment]
I fixed @felubra's bug (though I don't know why it occurred). Will go live with version 0.8.5. But I believe it's unrelated to yours @M53. I will have to take another look.
