### ISSUE TITLE
Error while upgrading to 8.7 on Ubuntu

### ISSUE THREAD

**Issue by danmou** [fman-community/fman#300]
I got the following error while upgrading from 8.5 to 8.7 through apt:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  fman
1 upgraded, 0 newly installed, 0 to remove and 101 not upgraded.
1 not fully installed or removed.
Need to get 41.4 MB of archives.
After this operation, 1,024 B of additional disk space will be used.
Get:1 https://fman.io/updates/ubuntu stable/main amd64 fman amd64 0.8.7 [41.4 MB]
Fetched 41.4 MB in 17s (2,363 kB/s)                                                                      
(Reading database ... 602113 files and directories currently installed.)
Preparing to unpack .../archives/fman_0.8.7_amd64.deb ...
Unpacking fman (0.8.7) over (0.8.5) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Setting up update-notifier-common (3.168.7) ...
Traceback (most recent call last):
  File "/usr/lib/update-notifier/package-data-downloader", line 24, in <module>
    import debian.deb822
  File "/usr/lib/python3/dist-packages/debian/deb822.py", line 38, in <module>
    import chardet
ImportError: No module named 'chardet'
dpkg: error processing package update-notifier-common (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up fman (0.8.7) ...
Errors were encountered while processing:
 update-notifier-common
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The upgrade still succeeded and fman seems to be working fine.

**Comment by mherrmann** [comment]
Thank you for the report. I don't think this is a bug of fman. The error you posted seems to indicate that the problem lies in `/usr/lib/python3/dist-packages/debian/deb822.py` and `/usr/lib/update-notifier/package-data-downloader`, which are both external to fman.

**Comment by danmou** [comment]
You're right, I mistakenly thought the update-notifier was some part of fman. After some further investigation I found that running `sudo apt install --reinstall python3-chardet` resolved the issue.
