### ISSUE TITLE
[Bug] Bad Error dialog when running `install plugins` from command prompt

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#331]
I went to check to see if there are any new plugins with the `install plugins` command on the command prompt. It is consistantly giving me this error:

Command 'InstallPlugin' raised error.

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 601, in urlopen
  File "urllib3/connectionpool.py", line 346, in _make_request
  File "urllib3/connectionpool.py", line 850, in _validate_conn
  File "urllib3/connection.py", line 326, in connect
  File "urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
  File "ssl.py", line 385, in wrap_socket
  File "ssl.py", line 760, in __init__
  File "ssl.py", line 996, in do_handshake
  File "ssl.py", line 641, in do_handshake
ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 440, in send
  File "urllib3/connectionpool.py", line 639, in urlopen
  File "urllib3/util/retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /search/repositories?q=topic:fman+topic:plugin&per_page=100&page=1 (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:720)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 289, in _run_in_thread
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/commands.py", line 1309, in __call__
    self._plugin_repos = find_repos(topics=['fman', 'plugin'])
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/github.py", line 10, in find_repos
    return list(map(GitHubRepo, _fetch_all_pages(url)))
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/github.py", line 14, in _fetch_all_pages
    data = _get_json(json_url + '&per_page=%d&page=%d' % (page_size, page))
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/github.py", line 69, in _get_json
    return _get(url).json()
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/github.py", line 72, in _get
    response = requests.get(url)
  File "requests/api.py", line 72, in get
  File "requests/api.py", line 58, in request
  File "requests/sessions.py", line 508, in request
  File "requests/sessions.py", line 618, in send
  File "requests/adapters.py", line 506, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /search/repositories?q=topic:fman+topic:plugin&per_page=100&page=1 (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:720)'),))

I'm traveling right now and using a slow cell phone based WiFi hotspot. But, it is saying that the hits to GitHub have been too much (Maybe my TextBar scripts are checking too often). fman should catch these errors and display a nicer dialog prompt explaining the issue.

**Comment by mherrmann** [comment]
Thanks. It's an issue with SSL certificates / macOS's OpenSSL version. I already have a fix and will release it later today.

**Comment by raguay** [comment]
Okay. Thanks.

**Comment by mherrmann** [comment]
[fman 0.9.1](https://fman.io/changelog#v0.9.1) is out and fixes the issue :-)

**Comment by raguay** [comment]
Yep. It works fine now. Thanks.

**Comment by mherrmann** [comment]
Cool :-)

**Comment by evanre** [comment]
Hi, @mherrmann I've got the same error in 1.1.1 version on fresh install of macOS Sierra 10.12.16
`Command 'InstallPlugin' raised error.

Traceback (most recent call last):
  File "urllib/request.py", line 1254, in do_open
  File "http/client.py", line 1107, in request
  File "http/client.py", line 1152, in _send_request
  File "http/client.py", line 1103, in endheaders
  File "http/client.py", line 934, in _send_output
  File "http/client.py", line 877, in send
  File "http/client.py", line 1261, in connect
  File "ssl.py", line 385, in wrap_socket
  File "ssl.py", line 760, in __init__
  File "ssl.py", line 996, in do_handshake
  File "ssl.py", line 641, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:719)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fman/impl/plugins/command_registry.py", line 52, in _execute_command
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/commands/__init__.py", line 1458, in __call__
    self._plugin_repos = find_repos(topics=['fman', 'plugin'])
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/github.py", line 11, in find_repos
    return list(map(GitHubRepo, _fetch_all_pages(url)))
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/github.py", line 15, in _fetch_all_pages
    data = _get_json(json_url + '&per_page=%d&page=%d' % (page_size, page))
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/github.py", line 70, in _get_json
    return json.loads(_get(url).decode('utf-8'))
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/github.py", line 73, in _get
    return urlopen(url).read()
  File "urllib/request.py", line 163, in urlopen
  File "urllib/request.py", line 466, in open
  File "urllib/request.py", line 484, in _open
  File "urllib/request.py", line 444, in _call_chain
  File "urllib/request.py", line 1297, in https_open
  File "urllib/request.py", line 1256, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:719)>`

**Comment by mherrmann** [comment]
Actually @evanre yours is a different error (`CERTIFICATE_VERIFY_FAILED` vs `TLSV1_ALERT_PROTOCOL_VERSION`). I'll open a new issue. Sorry for the inconvenience and thank you for reporting :-)

**Comment by mherrmann** [comment]
New issue: #432
