### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by abuzze** [fman-community/fman#347]
I started fman on MacOS 10.12.6. and it crashed with no visible error message and this error in the logs.

```
Mar 27 11:00:52 isengard com.apple.xpc.launchd[1] (io.fman.fman.16656[4723]): Service exited with abnormal code: 255
Mar 27 11:01:04 isengard com.apple.xpc.launchd[1] (io.fman.fman.16656[4726]): Service exited with abnormal code: 255
Mar 27 11:03:21 isengard com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000050.fman[5250]): Service exited with abnormal code: 255
Mar 27 11:03:34 isengard com.apple.xpc.launchd[1] (io.fman.fman.16692[5262]): Service exited with abnormal code: 255
```

I started the app via terminal and saw this error
```

$  /Applications/fman.app/Contents/MacOS/fman
Traceback (most recent call last):
  File "fman/main.py", line 11, in <module>
  File "fman/main.py", line 7, in main
  File "fman/impl/application_context.py", line 56, in run
  File "fman/impl/application_context.py", line 408, in excepthook
  File "fman/impl/application_context.py", line 214, in plugin_dirs
  File "os.py", line 231, in makedirs
  File "os.py", line 231, in makedirs
  File "os.py", line 241, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/Library/Application Support/fman/Plugins'
[5530] Failed to execute script main
```

I recreated the directory ('/Users/username/Library/Application Support/fman/) to fix this. But it think it's better to inform the user somehow, why the app won't start, or just create the directory and move on.

**Comment by mherrmann** [comment]
That's strange. Because fman does create the directory. In fact, that's precisely where the error occurred: `makedirs` in the error log was fman's attempt to create the directory (and missing parent directories), which failed. :thinking:
