### ISSUE TITLE
Plugin DropboxConnect failed to load

### ISSUE THREAD

**Issue by nimafazeli** [fman-community/fman#350]
On a first install after trying to copy a file from my dropbox, I got a `no such file exists`. 

I thought it needs the dropbox plugin so I went ahead and installed it. On reload I got this

```
Plugin 'DropboxConnect' failed to load.

Traceback (most recent call last):
  File "C:\Users\nima\AppData\Roaming\fman\Plugins\Third-party\DropboxConnect/dropbox-sdk-python\pkg_resources\__init__.py", line 474, in get_build_platform
    from sysconfig import get_platform
ImportError: No module named 'sysconfig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 146, in load
  File "fman\impl\plugins\plugin.py", line 161, in _load
  File "fman\impl\plugins\plugin.py", line 176, in _load_classes
  File "fman\impl\plugins\plugin.py", line 228, in _load_packages
  File "<frozen importlib._bootstrap_external>", line 418, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 841, in load_module
  File "<frozen importlib._bootstrap_external>", line 700, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\nima\AppData\Roaming\fman\Plugins\Third-party\DropboxConnect\dropboxconnect\__init__.py", line 17, in <module>
    import dropbox
  File "C:\Users\nima\AppData\Roaming\fman\Plugins\Third-party\DropboxConnect/dropbox-sdk-python\dropbox\__init__.py", line 3, in <module>
    from .dropbox import __version__, Dropbox, DropboxTeam, create_session  # noqa: F401
  File "C:\Users\nima\AppData\Roaming\fman\Plugins\Third-party\DropboxConnect/dropbox-sdk-python\dropbox\dropbox.py", line 35, in <module>
    from .session import (
  File "C:\Users\nima\AppData\Roaming\fman\Plugins\Third-party\DropboxConnect/dropbox-sdk-python\dropbox\session.py", line 1, in <module>
    import pkg_resources
  File "C:\Users\nima\AppData\Roaming\fman\Plugins\Third-party\DropboxConnect/dropbox-sdk-python\pkg_resources\__init__.py", line 1040, in <module>
    class Environment(object):
  File "C:\Users\nima\AppData\Roaming\fman\Plugins\Third-party\DropboxConnect/dropbox-sdk-python\pkg_resources\__init__.py", line 1043, in Environment
    def __init__(self, search_path=None, platform=get_supported_platform(),
  File "C:\Users\nima\AppData\Roaming\fman\Plugins\Third-party\DropboxConnect/dropbox-sdk-python\pkg_resources\__init__.py", line 272, in get_supported_platform
    plat = get_build_platform()
  File "C:\Users\nima\AppData\Roaming\fman\Plugins\Third-party\DropboxConnect/dropbox-sdk-python\pkg_resources\__init__.py", line 476, in get_build_platform
    from distutils.util import get_platform
ImportError: No module named 'distutils.util'

```
I am on a windows 10 machine

**Comment by mherrmann** [comment]
Hi! The DropboxConnect plugin is not maintained by me (fman's author) but by @raguay. In fact, the error you reported is already reported on [DropboxConnect's issue tracker](https://github.com/raguay/DropboxConnect/issues/4). I'd kindly ask you to please continue the discussion there.
