### ISSUE TITLE
No meaningful error message when deleting files in use

### ISSUE THREAD

**Issue by IgorKrupenja** [fman-community/fman#366]
Setup:
fman v1.0.0 running as Administrator on Windows 10 Home x64, build 16299.371.

Steps:
1. Try deleting a file in use (e.g. mounted ISO image).

Result:
Error message is not meaningful:
```
Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 286, in _run_in_thread
  File "C:\Users\igork\AppData\Local\fman\Versions\1.0.0\Plugins\Core\core\commands.py", line 105, in __call__
    move_to_trash(url)
  File "fman\fs.py", line 29, in move_to_trash
  File "fman\impl\plugins\mother_fs.py", line 95, in move_to_trash
  File "C:\Users\igork\AppData\Local\fman\Versions\1.0.0\Plugins\Core\core\fs\local\__init__.py", line 67, in move_to_trash
    move_to_trash(self._url_to_os_path(path))
  File "C:\Users\igork\AppData\Local\fman\Versions\1.0.0\Plugins\Core\core\trash.py", line 9, in move_to_trash
    send2trash(file)
  File "C:\Users\igork\AppData\Local\fman\Versions\1.0.0\Plugins\Core\send2trash\plat_win.py", line 70, in send2trash
    raise WindowsError(None, None, path, result)
PermissionError: [WinError 32] None: 'C:\\Users\\igork\\Downloads\\en_visio_professional_2016_x86_x64_dvd_6962139.iso'
```

Better to have something like the error message in Win Explorer, saying "file is open in..." or similar. Probably not high priority though.

**Comment by mherrmann** [comment]
Good suggestion. I implemented this now so it says

> Could not delete en_visio_professional_2016_x86_x64_dvd_6962139.iso: Permission denied. Do you want to continue?

![delete-error-permission-denied](https://user-images.githubusercontent.com/1076393/39042137-69da1cb4-448a-11e8-8795-9c160dd26a12.png)

Will go live with 1.0.1.

**Comment by mherrmann** [comment]
Implemented in [fman 1.0.1](https://fman.io/changelog#v1.0.1).

**Comment by kek91** [comment]
Is it possible to distinguish between "no permission" (as in no modify/write-access on the file) and "file is locked/in use"?

**Comment by mherrmann** [comment]
@kek91 it's surprisingly difficult. I created a new issue (#384) for this.
