### ISSUE TITLE
fman 1.0 error: Column 'Name' raised error due to background task deleting files.

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#370]
While running terminal commands, fman keeps coming up with this error dialogue. It's only been happening since 1.0. Evidently, the brew commands (which run shell scripts) are creating and destroying files in the home folder that fman then looses track of and errors out.

Column 'Name' raised error.

Traceback (most recent call last):
  File "fman/impl/model/base.py", line 234, in reload
KeyError: 'file:///Users/raguay/.z.23210'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fman/impl/fs_cache.py", line 24, in query
KeyError: '/Users/raguay/.z.23210'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 388, in get_sort_value
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/__init__.py", line 21, in get_sort_value
    is_dir = self._fs.is_dir(url)
  File "fman/fs.py", line 23, in is_dir
  File "fman/impl/plugins/mother_fs.py", line 58, in is_dir
  File "fman/impl/plugins/mother_fs.py", line 56, in query
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/local/__init__.py", line 43, in is_dir
    return S_ISDIR(self.stat(existing_path).st_mode)
  File "fman/fs.py", line 135, in wrapper
  File "fman/impl/fs_cache.py", line 26, in query
  File "fman/fs.py", line 135, in <lambda>
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/local/__init__.py", line 46, in stat
    return os.stat(self._url_to_os_path(path))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/raguay/.z.23210'

**Comment by mherrmann** [comment]
Thank you Richard. This should already be fixed, by [fman 1.0.1](https://fman.io/changelog). Does it still occur for you?

**Comment by raguay** [comment]
Okay. Since it finally updated, it hasn't had the error. It usually manifest while building my Vue.js project, but I've rebuilt it several times now and no errors. So, I guess it's fixed. I'll keep hammering at it.

**Comment by mherrmann** [comment]
Okay. Sounds like updating is continuing to be a pain for you, sorry. If the problem with the Name column does appear again for you let me know.
