### ISSUE TITLE
fman version 1.0.9 won't start on Arch Linux, installed from AUR

### ISSUE THREAD

**Issue by semanticdreamer** [fman-community/fman#401]
The `fman` command just exits immediately without any errors, also nothing in the logs… though `fman --help` works as expected.

Running `/opt/fman/fman` unveils what seems to be the root cause:

```
Traceback (most recent call last):
  File "fbs_runtime/signal_.py", line 2, in <module>
  File "/root/dev/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /opt/fman/PyQt5.QtNetwork.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fman/main.py", line 1, in <module>
  File "/root/dev/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fman/__init__.py", line 1, in <module>
  File "/root/dev/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fman/clipboard.py", line 3, in <module>
  File "/root/dev/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fman/impl/util/__init__.py", line 1, in <module>
  File "/root/dev/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fbs_runtime/application_context.py", line 2, in <module>
  File "/root/dev/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fbs_runtime/signal_.py", line 4, in <module>
ModuleNotFoundError: No module named 'PySide2'
[5092] Failed to execute script main
```

Maybe an issue w/ AUR packaging?

OS: Arch Linux
Kernel: x86_64 Linux 4.16.3-1-ARCH
fman version 1.0.9

**Comment by mherrmann** [comment]
I cannot reproduce this I'm afraid. I was able to download, install and start fman on an up-to-date Arch KDE VM, both from the AUR and via fman's own [.pkg.tar.xz](http://download.fman.io/fman.pkg.tar.xz). There was an intermittent problem with the release of 1.0.9 on Friday though. Does the .pkg.tar.xz I just linked to work for you?

**Comment by mherrmann** [comment]
One thing that is interesting though is that `/opt/fman/PyQt5.QtNetwork.so` mentioned in the error log should not be there. Investigating further...

**Comment by mherrmann** [comment]
What I don't understand is why `/usr/lib/libQt5Core.so.5` is being loaded at all. It should load `/opt/fman/PyQt5.QtCore.so` instead. Do you have this file @semanticdreamer? Is your Arch setup pretty vanilla or did you make any changes to the library path?

**Comment by semanticdreamer** [comment]
First of, THX @mherrmann for looking into this!

My Arch install should indeed be pretty vanilla. BUT nevertheless I quickly cross-checked the usual suspects and didn't find any custom path setting or overwrite. Is there any particular env var  that I could check for?

And yes, I have the file `/opt/fman/PyQt5.QtCore.so`.

Yes, really strange indeed. I tried to exec the binary w/ env vars set but didn't succeed.

(strange thing: it totally worked FOR MONTH, That said, I'm kind of "sure" that if it is related to my env it must have come from an update, though still strange)

**Comment by semanticdreamer** [comment]
@mherrmann :see_no_evil: it seems indeed that my Arch package env was "broken". Somehow. Unfort. I can not really tell anything more specific, but a forced system update fixed it for me.  

Could be, that it's still loading from `/usr/lib/libQt5Core.so.5`, but as also this lib got updated, so…

Again, THX a ton from a YAHFS (Yet Another Happy Fman Subscriber) :smile: for taking your time to look into this — actually, appologies for having asked in the first place, b/c in the end it really didn't seem to be an issue of the `fman` AUR package at all.

**Comment by mherrmann** [comment]
No problem! I'm happy to hear it is working for you now :-)
