### ISSUE TITLE
How to "Open with..." program with parameters

### ISSUE THREAD

**Issue by MikiGrit** [fman-community/fman#420]
I want to open file with program, that uses parameters (e.g. "flatpak run org.videolan.VLC"). But such command cannot be added through app and when I manually edit "Apps (Linux).json" it shows:
```
Command 'OpenWith' raised error.

Traceback (most recent call last):
  File "fman/impl/plugins/command_registry.py", line 97, in _execute_command
  File "/opt/fman/Plugins/Core/core/commands/__init__.py", line 1906, in __call__
    ShowAppsForOpening(files).show()
  File "/opt/fman/Plugins/Core/core/commands/__init__.py", line 2002, in show
    self.on_selected(option)
  File "/opt/fman/Plugins/Core/core/commands/__init__.py", line 2053, in on_selected
    _open_files_with_app(self._files, option)
  File "/opt/fman/Plugins/Core/core/commands/__init__.py", line 1948, in _open_files_with_app
    Popen(**get_popen_kwargs_for_opening(files, with_=app_path))
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 1289, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/flatpak run org.videolan.VLC'
```

**Comment by mherrmann** [comment]
The current form of `Apps (Linux).json` does not allow supplying parameters I'm afraid. But! Shouldn't you be able to write a shell script that does it?

```
#!/bin/bash
/usr/bin/flatpak run org.videolan.VLC $1
```

Save as a `.sh` file, make executable with `chmod u+x file.sh` then in `Apps.json` add `"VLC": "/path/to/file.sh"`.

**Comment by MikiGrit** [comment]
Oh, that solves it! Thanks :). But will be somewhat tedious to write for every app :).

**Comment by mherrmann** [comment]
I understand. But I'm happy to hear it can serve as a workaround :-)

**Comment by SlimerDude** [comment]
On windows, this workaround is quite slow and clunky - what with console windows flashing open and closing - so I'd still like to +1 this request.
