### ISSUE TITLE
Error with InstallPlugin command

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#447]
Reported by a user on Windows 10:

```
Command 'InstallPlugin' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 52, in _execute_command
  File "C:\Users\...\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\commands\__init__.py", line 1533, in __call__
    plugin_dir = self._install_plugin(repo.name, zipball_contents)
  File "C:\Users\...\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\commands\__init__.py", line 1569, in _install_plugin
    copy(join(zip_url, dir_in_zip), dest_dir_url)
  File "fman\fs.py", line 49, in copy
  File "fman\impl\plugins\mother_fs.py", line 129, in copy
  File "C:\Users\...\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\fs\zip.py", line 94, in copy
    task()
  File "C:\Users\...\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\fs\zip.py", line 334, in __call__
    _run_7zip(args)
  File "C:\Users\...\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\fs\zip.py", line 414, in _run_7zip
    pass
  File "C:\Users\...\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\fs\zip.py", line 456, in __exit__
    raise CalledProcessError(exit_code, self._args)
    subprocess.CalledProcessError: Command '['x', 'C:/Users/.../AppData/Local/Temp/tmpc0gzijou/plugin.zip', 'oskretc-fman-flatview-e8f28b2', '-o.\\qm1fgqlo.tmp']' returned non-zero exit status 2
```

Interestingly, opening and extracting Zip files does work.

**Comment by zeddyblue** [comment]
I am getting something similar on Windows 10

Command 'InstallPlugin' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 52, in _execute_command
  File "C:\Users\dinev\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\commands\__init__.py", line 1533, in __call__
    plugin_dir = self._install_plugin(repo.name, zipball_contents)
  File "C:\Users\dinev\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\commands\__init__.py", line 1569, in _install_plugin
    copy(join(zip_url, dir_in_zip), dest_dir_url)
  File "fman\fs.py", line 49, in copy
  File "fman\impl\plugins\mother_fs.py", line 129, in copy
  File "C:\Users\dinev\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\fs\zip.py", line 94, in copy
    task()
  File "C:\Users\dinev\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\fs\zip.py", line 334, in __call__
    _run_7zip(args)
  File "C:\Users\dinev\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\fs\zip.py", line 414, in _run_7zip
    pass
  File "C:\Users\dinev\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\fs\zip.py", line 456, in __exit__
    raise CalledProcessError(exit_code, self._args)
subprocess.CalledProcessError: Command '['x', 'C:/Users/dinev/AppData/Local/Temp/tmpa8o_p9sd/plugin.zip', 'crimoniv-FTPClient-e3953d1', '-o.\\0j9xj04d.tmp']' returned non-zero exit status 2

**Comment by mherrmann** [comment]
Thanks for letting me know! Are you able to open and extract Zip files with fman?

**Comment by zeddyblue** [comment]
Do I need a plugin to extract? I've only had fman installed for a day and this was my first attempt to install a plugin. I was able to click on a zip file and see its content within fman.

**Comment by mherrmann** [comment]
Thanks - you don't need a plugin to extract. Press F5 to copy (=extract) the currently selected file to the other side.

**Comment by zeddyblue** [comment]
No, cant extract. I get this:

Command 'Copy' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 101, in _execute_command
  File "C:\Users\dinev\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\commands\__init__.py", line 470, in __call__
    self._call(files, dest_dir, src_dir, dest_name)
  File "C:\Users\dinev\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\commands\__init__.py", line 624, in _call
    submit_task(CopyFiles(files, dest_dir, src_dir, dest_name))
  File "fman\__init__.py", line 319, in submit_task
  File "C:\Users\dinev\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\fileoperations.py", line 48, in __call__
    self.run(task)
  File "fman\__init__.py", line 305, in run
  File "C:\Users\dinev\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\fs\zip.py", line 334, in __call__
    _run_7zip(args)
  File "C:\Users\dinev\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\fs\zip.py", line 414, in _run_7zip
    pass
  File "C:\Users\dinev\AppData\Local\fman\Versions\1.1.3\Plugins\Core\core\fs\zip.py", line 456, in __exit__
    raise CalledProcessError(exit_code, self._args)
subprocess.CalledProcessError: Command '['x', 'C:/Users/dinev/Downloads/wumt.zip', 'wumt_x64.exe', '-o.\\cy00lgep.tmp']' returned non-zero exit status 2

**Comment by mherrmann** [comment]
Okay. And the destination file also isn't created I presume? (Also not when you reload with <code>Ctrl+R</code>.)

**Comment by zeddyblue** [comment]
Correct. Nothing is created.

**Comment by mherrmann** [comment]
Okay, thanks :-)

**Comment by zeddyblue** [comment]
No worries. I will keep testing and purchase a license if I keep using it.

**Comment by mherrmann** [comment]
Cool. Thanks! :)

**Comment by zeddyblue** [comment]
Just tried again. Install plugin seems to be working

**Comment by mherrmann** [comment]
Okay. Still curious why you got the error in the first place. But I can't reproduce the issue so I'm closing it.

**Comment by mherrmann** [comment]
Now also encountered by @gilbertbw in #469. Reopening.

**Comment by mherrmann** [comment]
I believe I was able to find the root cause of this and implement a fix. Will go live with release 1.1.8.

**Comment by gilbertbw** [comment]
Thanks Michael!

**Comment by mherrmann** [comment]
[fman 1.1.8](https://fman.io/changelog#v1.1.8) is live. Does it work for you when you [update](https://fman.io/docs/automatic-updates) @gilbertbw?

**Comment by mherrmann** [comment]
(Closing the issue for now. It's still possible to comment.)
