### ISSUE TITLE
Install Plugin fails

### ISSUE THREAD

**Issue by gilbertbw** [fman-community/fman#469]
When running Install Plugin I get the following error:
```Command 'InstallPlugin' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 52, in _execute_command
  File "C:\Users\Gilbert\AppData\Local\fman\Versions\1.1.7\Plugins\Core\core\commands\__init__.py", line 1543, in __call__
    plugin_dir = self._install_plugin(repo.name, zipball_contents)
  File "C:\Users\Gilbert\AppData\Local\fman\Versions\1.1.7\Plugins\Core\core\commands\__init__.py", line 1579, in _install_plugin
    copy(join(zip_url, dir_in_zip), dest_dir_url)
  File "fman\fs.py", line 48, in copy
  File "fman\impl\plugins\mother_fs.py", line 129, in copy
  File "C:\Users\Gilbert\AppData\Local\fman\Versions\1.1.7\Plugins\Core\core\fs\zip.py", line 95, in copy
    task()
  File "C:\Users\Gilbert\AppData\Local\fman\Versions\1.1.7\Plugins\Core\core\fs\zip.py", line 335, in __call__
    _run_7zip(args)
  File "C:\Users\Gilbert\AppData\Local\fman\Versions\1.1.7\Plugins\Core\core\fs\zip.py", line 415, in _run_7zip
    pass
  File "C:\Users\Gilbert\AppData\Local\fman\Versions\1.1.7\Plugins\Core\core\fs\zip.py", line 461, in __exit__
    exit_code, self._args, ''.join(self._stdout_lines)
core.fs.zip._7zipError: 7-Zip with args ['x', 'C:/Users/Gilbert/AppData/Local/Temp/tmp9h8jui66/plugin.zip', 'raguay-favorites-a80312b', '-o.\\qxygtqs2.tmp'] returned non-zero exit status 2```

**Comment by mherrmann** [comment]
Sorry for the trouble Gilbert and thank you for reporting the issue. This seems to be the same as #447. Let's continue the discussion there please.
