### ISSUE TITLE
Access to empty CD-ROM-drive raises an error (fman 1.1.7 @ Windows)

### ISSUE THREAD

**Issue by kernal64** [fman-community/fman#474]
FileSystem 'LocalFileSystem' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 348, in iterdir
  File "C:\Program Files\fman\Versions\1.1.7\Plugins\Core\core\fs\local\__init__.py", line 37, in iterdir
    return os.listdir(self._url_to_os_path(path))
PermissionError: [WinError 21] The device is not ready: 'D:\\'

**Comment by mherrmann** [comment]
Does it work when you browse the CD-ROM with Explorer?

**Comment by kernal64** [comment]
Sorry, the title was not accurate. I just changed it. The error occurs, when I (accidentally) try to access my empty optical disk drive.

Windows Explorer presents me a meaningful dialog:
![image](https://user-images.githubusercontent.com/42241247/43962319-aa625d0c-9cb7-11e8-8f5d-ff8729a1575b.png)

Can you check an Alt-F1/2, if the selected drive supports removable media and if the drive is empty present a dialog stating this, instead of showing a traceback?
