### ISSUE TITLE
Font load error: Roboto Bold.ttf

### ISSUE THREAD

**Issue by ckm47** [fman-community/fman#491]
Windows 10
fman version 1.2.5

After opening fman I receive the following error message: 

> Could not load font C:\Users\cmui\AppData\Local\fman\Versions\1.2.5\Plugins\Core\Roboto Bold.ttf
> 
> Traceback (most recent call last):
>   File "fman\impl\plugins\plugin.py", line 152, in _load_font
>   File "fman\impl\util\qt\thread.py", line 11, in result
>   File "fman\impl\util\qt\thread.py", line 64, in run_in_thread
>   File "fman\impl\font_database.py", line 14, in load
> fman.impl.font_database.FontError: Font 'C:\\Users\\cmui\\AppData\\Local\\fman\\Versions\\1.2.5\\Plugins\\Core\\Roboto Bold.ttf' could not be loaded.

None of the program functionality appears to be affected.  I'm attaching the Roboto Bold.ttf file. 
[Roboto Bold.zip](https://github.com/fman-users/fman/files/2319122/Roboto.Bold.zip)

**Comment by mherrmann** [comment]
It seems like fman simply can't load .ttf fonts on your system (#480). Strange...

**Comment by StevenLu2004** [comment]
Somehow C:\Users\\*myusername*\AppData\Local\fman doesn't even exist for me, and fman just loads an ugly default font. I installed Roboto on my system, but still it didn't load. I had to change `font-family: "Roboto Bold";` to `font-family: Roboto; font-weight: bold;`.
