### ISSUE TITLE
Mac OSX—Move files to new dir returns error

### ISSUE THREAD

**Issue by so-lost** [fman-community/fman#524]
Trying to select files and then move to new directory but returns this error:
(changed my username to <username> in this post just to mask it)
Mac OSX 10.12.6
Fman v1.3.2

```
Command 'MoveToDir' raised error.

Traceback (most recent call last):
  File "fman/impl/fs_cache.py", line 36, in query
KeyError: 'stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/local/__init__.py", line 52, in stat
    return os.stat(os_path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/<username>/Pictures/Memes/testFolder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fman/impl/plugins/command_registry.py", line 110, in _execute_command
  File "/Users/<username>/Library/Application Support/fman/Plugins/Third-party/MoveToDir/movetodir/__init__.py", line 16, in __call__
    if not is_dir(newdirp):
  File "fman/fs.py", line 24, in is_dir
  File "fman/impl/plugins/mother_fs.py", line 62, in is_dir
  File "fman/impl/plugins/mother_fs.py", line 60, in query
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/local/__init__.py", line 45, in is_dir
    return S_ISDIR(self.stat(existing_path).st_mode)
  File "fman/fs.py", line 201, in wrapper
  File "fman/impl/fs_cache.py", line 12, in query
  File "fman/impl/fs_cache.py", line 38, in query
  File "fman/fs.py", line 201, in <lambda>
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/local/__init__.py", line 54, in stat
    return os.stat(os_path, follow_symlinks=False)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/<username>/Pictures/Memes/testFolder'

**Comment by mherrmann** [comment]
This is a bug of the MoveToDir plugin, and not of fman. I see you've already raised the same issue there. Closing this one.
