### ISSUE TITLE
InstallPlugin command fails on Fedora 29

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#563]
Traceback (most recent call last):
      File "fman/impl/plugins/command_registry.py", line 66, in _execute_command
      File "/opt/fman/Plugins/Core/core/commands/__init__.py", line 1572, in __call__
        find_repos(topics=['fman', 'plugin'])
      File "/opt/fman/Plugins/Core/core/github.py", line 13, in find_repos
        return list(map(GitHubRepo, _fetch_all_pages(url)))
      File "/opt/fman/Plugins/Core/core/github.py", line 17, in _fetch_all_pages
        data = _get_json(json_url + '&per_page=%d&page=%d' % (page_size, page))
      File "/opt/fman/Plugins/Core/core/github.py", line 72, in _get_json
        return json.loads(_get(url).decode('utf-8'))
      File "/opt/fman/Plugins/Core/core/github.py", line 76, in _get
        return urlopen(url).read()
      File "urllib/request.py", line 163, in urlopen
      File "urllib/request.py", line 466, in open
      File "urllib/request.py", line 484, in _open
      File "urllib/request.py", line 444, in _call_chain
      File "urllib/request.py", line 1297, in https_open
      File "urllib/request.py", line 1223, in do_open
      File "http/client.py", line 1238, in __init__
      File "ssl.py", line 449, in create_default_context
      File "ssl.py", line 369, in __new__
    ssl.SSLError: ('failed to allocate SSL context',)

(Error originally posted in #561.)

**Comment by brunojm** [comment]
Hello @mherrmann just FYI: tried something like this: http://sgros.blogspot.com/2017/08/viber-and-fedora-26-ssl-errors.html and now it's working

**Comment by mherrmann** [comment]
Thank you @brunojm. Your hint let me (I hope) fix this issue in [fman 1.4.5](https://fman.io/changelog#v1.4.5). If it still occurs for you, please do let me know.

**Comment by brunojm** [comment]
@mherrmann I update to 1.4.5 and now it's working fine. Thank you.

**Comment by mherrmann** [comment]
Happy to hear it! Thanks :-)
