### ISSUE TITLE
Exception on copying from a WebDAV network drive

### ISSUE THREAD

**Issue by ghost** [fman-community/fman#564]
Hi!

I'm not sure is this a bug or a not-yet-ready feature (#33), so I create a new ticket. I got an exception in Windows version after I'd tried to copy a directory (`Z:\backup\`) from a network drive (WebDAV) to an internal HDD. WebDAV provider is Yandex.Disk.

```
Command 'Copy' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 128, in _execute_command
  File "C:\Users\EvgeniiChernyi\AppData\Local\fman\Versions\1.4.3\Plugins\Core\core\commands\__init__.py", line 502, in __call__
    proceed = self._confirm_tree_operation(files, dest_dir, src_dir)
  File "C:\Users\EvgeniiChernyi\AppData\Local\fman\Versions\1.4.3\Plugins\Core\core\commands\__init__.py", line 575, in _confirm_tree_operation
    if len(files) == 1 and fs.samefile(dest_url, files[0]):
  File "fman\fs.py", line 45, in samefile
  File "fman\impl\plugins\mother_fs.py", line 123, in samefile
  File "fman\impl\plugins\mother_fs.py", line 120, in resolve
  File "C:\Users\EvgeniiChernyi\AppData\Local\fman\Versions\1.4.3\Plugins\Core\core\fs\local\__init__.py", line 180, in resolve
    path = Path(path).resolve()
  File "pathlib.py", line 1109, in resolve
  File "pathlib.py", line 186, in resolve
OSError: [WinError 1] Incorrect function: 'Z:\\backup'
```

**Comment by mherrmann** [comment]
Thank you for the report. I'd say an error message with a traceback is a bug. But obviously, it's caused by the lack of WebDAV support. Now you've linked it to #33, I'll know to watch out for this case when implementing it. Thanks!
