### ISSUE TITLE
Fman error message when attempting to move files (F6) 

### ISSUE THREAD

**Issue by sebgulliver** [fman-community/fman#576]
Command 'Move' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 128, in _execute_command
  File "C:\Users\SG\AppData\Local\fman\Versions\1.4.4\Plugins\Core\core\commands\__init__.py", line 502, in __call__
    proceed = self._confirm_tree_operation(files, dest_dir, src_dir)
  File "C:\Users\SG\AppData\Local\fman\Versions\1.4.4\Plugins\Core\core\commands\__init__.py", line 580, in _confirm_tree_operation
    if is_parent(file_, dest_url, fs):
  File "C:\Users\SG\AppData\Local\fman\Versions\1.4.4\Plugins\Core\core\util.py", line 40, in is_parent
    if fs.samefile(parent_url, dir_url):
  File "fman\fs.py", line 43, in samefile
  File "fman\impl\plugins\mother_fs.py", line 122, in samefile
  File "fman\impl\plugins\mother_fs.py", line 120, in resolve
  File "C:\Users\SG\AppData\Local\fman\Versions\1.4.4\Plugins\Core\core\fs\local\__init__.py", line 180, in resolve
    path = Path(path).resolve()
  File "pathlib.py", line 1109, in resolve
  File "pathlib.py", line 186, in resolve
OSError: [WinError 1] Incorrect function: 'Z:\\@forløb\\old\\virkelighedens helte'

**Comment by sebgulliver** [comment]
Error is not drive specific as first assumed

**Comment by mherrmann** [comment]
@sebgulliver Does it happen for all folders on `Z:\`, or just for `@forløb\`? I'm wondering if it's because of the special characters in this name.

**Comment by sebgulliver** [comment]
sorry for for sounding a little sour. Not being able to use Fman just frustrates.

There appears to be no difference when moving to and from folders without danish characters (se printout below)

Furthermore, II thought this was a z:\ drive problem, but as it turns out the exact same error occours in drive c:\.

Sebastian

Command 'Move' raised error.

Traceback (most recent call last):

File "fman\impl\plugins\command_registry.py", line 128, in _execute_command

File "C:\Users\SG\AppData\Local\fman\Versions\1.4.6\Plugins\Core\core\commands\__init__.py", line 503, in __call__

proceed = self._confirm_tree_operation(files, dest_dir, src_dir)

File "C:\Users\SG\AppData\Local\fman\Versions\1.4.6\Plugins\Core\core\commands\__init__.py", line 576, in _confirm_tree_operation

if len(files) == 1 and fs.samefile(dest_url, files[0]):

File "fman\fs.py", line 43, in samefile

File "fman\impl\plugins\mother_fs.py", line 122, in samefile

File "fman\impl\plugins\mother_fs.py", line 120, in resolve

File "C:\Users\SG\AppData\Local\fman\Versions\1.4.6\Plugins\Core\core\fs\local\__init__.py", line 185, in resolve

path = Path(path).resolve()

File "pathlib.py", line 1141, in resolve

File "pathlib.py", line 193, in resolve

OSError: [WinError 1] Incorrect function: 'Z:\\@inbox'

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mherrmann** [comment]
Thank you for the reply and sorry again for the trouble. In the error you just posted you were again on `Z:\` and in a path with a "special" character `@`. I presume that was a coincidence?

**Comment by sebgulliver** [comment]
That's it - moving to and from a folder without special characters, causes no problem. Doing so, though, was never a problem before.

Sebastian

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mherrmann** [comment]
I just released [fman 1.4.8](https://fman.io/changelog#v1.4.8) with an attempt to fix the problem. Can you test and let me know whether it works for you @sebgulliver?

**Comment by sebgulliver** [comment]
It works! Thank you so much. Sterling service. Hope not to bother you again too soon.

Many regards

Sebastian

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mherrmann** [comment]
Happy to hear it! Thanks for letting me know.
