### ISSUE TITLE
ToggleHiddenFiles error

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#600]
1. Toggle hidden files so they are visible.
2. Run command `Reload plugins`
3. Toggle hidden files again.

This produces the following error:

    Command 'ToggleHiddenFiles' raised error.
    
    Traceback (most recent call last):
      File "fman/impl/plugins/command_registry.py", line 128, in _execute_command
      File "/opt/fman/Plugins/Core/core/commands/__init__.py", line 927, in __call__
        _toggle_hidden_files(self.pane, not _is_showing_hidden_files(self.pane))
      File "/opt/fman/Plugins/Core/core/commands/__init__.py", line 943, in _toggle_hidden_files
        pane._remove_filter(_hidden_file_filter)
      File "fman/__init__.py", line 96, in _remove_filter
      File "fman/impl/util/qt/thread.py", line 11, in result
      File "fman/impl/util/qt/thread.py", line 86, in run_in_thread
      File "fman/impl/util/qt/thread.py", line 111, in result
      File "fman/impl/util/qt/thread.py", line 99, in __call__
      File "fman/impl/widgets.py", line 136, in remove_filter
      File "fman/impl/model/__init__.py", line 142, in remove_filter
    ValueError: list.remove(x): x not in list

**Comment by mherrmann** [comment]
Fixed in [fman 1.5.1](https://fman.io/changelog#v1.5.1).
