### ISSUE TITLE
Exception on OpenFile command

### ISSUE THREAD

**Issue by ghost** [fman-community/fman#609]
The starcktrace is bellow. It mentions some access problems, but I can't understand what's wrong as I open those files in explorer just fine.

```
Command 'OpenFile' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 128, in _execute_command
  File "C:\Users\ch\AppData\Local\fman\Versions\1.5.2\Plugins\Core\core\commands\__init__.py", line 294, in __call__
    _open_files([url])
  File "C:\Users\ch\AppData\Local\fman\Versions\1.5.2\Plugins\Core\core\commands\__init__.py", line 323, in _open_files
    _open_local_file(path)
  File "C:\Users\ch\AppData\Local\fman\Versions\1.5.2\Plugins\Core\core\commands\__init__.py", line 341, in _open_local_file
    ShellExecute(0, None, path, None, cwd, SW_SHOWNORMAL)
pywintypes.error: (5, 'ShellExecute', 'Access is denied.')
```

**Comment by ghost** [comment]
Also getting a weird error, while trying to delete a folder:

![image](https://user-images.githubusercontent.com/1007225/50374236-f37b2000-0625-11e9-8b05-b167cc96d597.png)

UPD: Explorer deleted it just fine.

**Comment by mherrmann** [comment]
Are you also getting these errors when you run fman as Administrator?

**Comment by ghost** [comment]
Haven't tried at the time. But considering the explorer deleted the file without confirmation I can assume the error was caused not with the file modes.
