### ISSUE TITLE
Can't open/view files on USB device (phone)

### ISSUE THREAD

**Issue by lelas** [fman-community/fman#632]
I have my Samsung Galaxy S7 connected via USB (3). I have no problem accessing it and copying files (images/videos) to my PC running Windows 10 -- via File Explorer. I, however, haven't been able to browse the devices storage via fman.

After digging around for a while (granted, I am new to fman and Windows 10), I discovered the ALT+F1 shortcut to see devices. My Samsung 7 didn't appear in the list, so I tried a little workaround: I created a shortcut to the device in File Explorer and placed it on the Desktop, browsed to the desktop in fman and clicked on it.

I received the following error:

```
Command 'OpenFile' raised error.

Traceback (most recent call last):
  File "fman\impl\fs_cache.py", line 36, in query
KeyError: 'stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 128, in _execute_command
  File "C:\Users\lasse\AppData\Local\fman\Versions\1.5.7\Plugins\Core\core\commands\__init__.py", line 294, in __call__
    _open_files([url], self.pane)
  File "C:\Users\lasse\AppData\Local\fman\Versions\1.5.7\Plugins\Core\core\commands\__init__.py", line 322, in _open_files
    _open_local_files(local_file_paths, pane)
  File "C:\Users\lasse\AppData\Local\fman\Versions\1.5.7\Plugins\Core\core\commands\__init__.py", line 326, in _open_local_files
    _open_local_files_win(paths, pane)
  File "C:\Users\lasse\AppData\Local\fman\Versions\1.5.7\Plugins\Core\core\commands\__init__.py", line 350, in _open_local_files_win
    if is_dir(target_url):
  File "fman\fs.py", line 22, in is_dir
  File "fman\impl\plugins\mother_fs.py", line 62, in is_dir
  File "fman\impl\plugins\mother_fs.py", line 60, in query
  File "C:\Users\lasse\AppData\Local\fman\Versions\1.5.7\Plugins\Core\core\fs\local\__init__.py", line 46, in is_dir
    return S_ISDIR(self.stat(existing_path).st_mode)
  File "fman\fs.py", line 199, in wrapper
  File "fman\impl\fs_cache.py", line 12, in query
  File "fman\impl\fs_cache.py", line 38, in query
  File "fman\fs.py", line 199, in <lambda>
  File "C:\Users\lasse\AppData\Local\fman\Versions\1.5.7\Plugins\Core\core\fs\local\__init__.py", line 51, in stat
    raise filenotfounderror(path)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by mherrmann** [comment]
Sorry for the trouble and thank you for reporting this. Did the shortcut have the `.lnk` extension?

**Comment by lelas** [comment]
Thanks for the quick response, Michael. 

No problem. I still can't find and access the device via fman. However, I suspect that the problems lies mainly in the chair, not in the computer. That said, a few words in the documentation describing the inability to access phones connected via USB (if that's really the case) would be good. I have been a Mac (and Ubuntu for web dev/servers) user in the past 8-9 years, so I am wee bit behind on Windows.

Yes, the shortcut has the .lnk extension. This is the path it contains:

`This PC\Samsung Galaxy S7`

Looking at it now, it makes sense that a cross-platform application doesn't cater to or care about Windows' naming of drives. I guess that's not the main problem here, although it could lead to a lot of Windows users poking around in vain in fman and requesting help, e.g. here (guilty!).

The issue is more likely that phones doesn't connect to a PC/Windows the same way an external harddrive or USB flash drive does. _'Open in fman'_ doesn't appear in File Explorers context menu either when right clicking on the device or any folder on it. I tried all USB connection types (it was initially set to 'Transfer files'), but no dice. If the device was or could be mounted, it would probably be a different story.
