### ISSUE TITLE
Error message: "gotolistener" raised error

### ISSUE THREAD

**Issue by lepicsaintloup** [fman-community/fman#677]
I get this on every command:

```
DirectoryPaneListener 'GoToListener' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 311, in _notify_listener_in_thread
  File "C:\Users\****\AppData\Local\fman\Versions\1.6.5\Plugins\Core\core\commands\goto.py", line 148, in on_path_changed
    load_json('Visited Paths.json', default={}, save_on_quit=True)
  File "fman\__init__.py", line 213, in load_json
  File "fman\impl\plugins\__init__.py", line 37, in load_json
  File "fman\impl\plugins\config.py", line 27, in load_json
  File "fman\impl\plugins\config.py", line 91, in load_json
  File "json\__init__.py", line 299, in load
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mherrmann** [comment]
Please close fman, then delete `Visited Paths.json` and its variants `Visited Paths (Windows).json`... in your [data directory](https://fman.io/docs/data-directory).
