### ISSUE TITLE
Windows *.lnk shortcuts don't open

### ISSUE THREAD

**Issue by GameLostException** [fman-community/fman#703]
Hello,

I've got several shortcuts on my Desktop linking to applications (e.g. Eclipse, Notepad++, etc.) and plain folders.
When trying to open them via fman, the app or folder fails to actually open/start and fman shows an error dialog. Links to files work OK though, i.e. it would correctly open the file within the ad-hoc app.

The error I get on app and folders shortcuts:
```
Command 'OpenFile' raised error.

Traceback (most recent call last):
  File "fman\impl\fs_cache.py", line 36, in query
KeyError: 'stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\auser\AppData\Local\fman\Versions\1.6.6\Plugins\Core\core\fs\local\__init__.py", line 53, in stat
    return os.stat(os_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Eclipse\\java-mars\\eclipse\\eclipse.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 128, in _execute_command
  File "C:\Users\auser\AppData\Local\fman\Versions\1.6.6\Plugins\Core\core\commands\__init__.py", line 294, in __call__
    _open_files([url], self.pane)
  File "C:\Users\auser\AppData\Local\fman\Versions\1.6.6\Plugins\Core\core\commands\__init__.py", line 327, in _open_files
    _open_local_files(local_file_paths, pane)
  File "C:\Users\auser\AppData\Local\fman\Versions\1.6.6\Plugins\Core\core\commands\__init__.py", line 331, in _open_local_files
    _open_local_files_win(paths, pane)
  File "C:\Users\auser\AppData\Local\fman\Versions\1.6.6\Plugins\Core\core\commands\__init__.py", line 355, in _open_local_files_win
    if is_dir(target_url):
  File "fman\fs.py", line 22, in is_dir
  File "fman\impl\plugins\mother_fs.py", line 62, in is_dir
  File "fman\impl\plugins\mother_fs.py", line 60, in query
  File "C:\Users\auser\AppData\Local\fman\Versions\1.6.6\Plugins\Core\core\fs\local\__init__.py", line 46, in is_dir
    return S_ISDIR(self.stat(existing_path).st_mode)
  File "fman\fs.py", line 199, in wrapper
  File "fman\impl\fs_cache.py", line 12, in query
  File "fman\impl\fs_cache.py", line 38, in query
  File "fman\fs.py", line 199, in <lambda>
  File "C:\Users\auser\AppData\Local\fman\Versions\1.6.6\Plugins\Core\core\fs\local\__init__.py", line 55, in stat
    return os.stat(os_path, follow_symlinks=False)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Eclipse\\java-mars\\eclipse\\eclipse.exe'
```

Some info about my system:
Windows 10 Pro
Version 1903
OS build 18362.388

fman version: 1.6.6
Not registered.

FYI, I've just starting using fman to evaluate an alternative to the native MS file explorer and it does quite fantastic. This issue however would be a deal blocker for my day2day usage.

**Comment by Arty2** [comment]
Cannot replicate on v1.7.2

**Comment by anonymous1184** [comment]
@Arty2 

It is a bug and replicable, but OP omitted an important detail... the issue only appears for WoW64 redirection. `fman.exe` being an x86 looks for `%ProgramFiles%` but it gets redirected to `%ProgramFiles(x86)%`. It needs to look for `%ProgramW6432%` or better yet a x64 version.
