### ISSUE TITLE
fman doesn't start on some Mac systems

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#707]
Reported by a user: Starting fman simply does nothing. Executing `/Applications/fman.app/Contents/MacOS/fman` via the Terminal gives:

```
Traceback (most recent call last): 
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 127, in <module> 
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load 
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked 
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked 
  File "/Users/michael/dev/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module 
  File "ctypes/__init__.py", line 538, in <module> 
  File "ctypes/__init__.py", line 273, in _reset_cache 
MemoryError 
[13379] Failed to execute script pyiboot01_bootstrap 
```

The user's OS was macOS Catalina.

**Comment by mherrmann** [comment]
Another user reported this on macOS Mojave.

A temporary workaround to this is to [disable automatic updates](https://fman.io/docs/automatic-updates) and [download fman 1.6.6](http://download.fman.io/1.6.6/fman.dmg).

**Comment by f8ttyc8t** [comment]
Thanks for the hint - works great that way!

Great tool anyway, loving it 👍

**Comment by mherrmann** [comment]
Because it seems to affect many people, I am looking into this. Unfortunately, I cannot reproduce it on my macOS Sierra, High Sierra, Mojave and Catalina test systems. I am working on getting access to another Mojave test system, in the hope of being able to reproduce it there.

**Comment by f8ttyc8t** [comment]
Could it be somehow related to using MacOS / homebrew / pyenv?

(I‘m just wild-guessing, but this is the only thing my Mac has special. At least I think so...)

**Comment by mherrmann** [comment]
I just released [fman 1.6.9](https://fman.io/blog/fman-works-again-on-macos-mojave/). Hopefully it will fix the issue. If it doesn't please let me know.

**Comment by f8ttyc8t** [comment]
1.6.9 works for me. Thanks!!

**Comment by genecivillico** [comment]
Me too - thank you for the fix!

**Comment by mherrmann** [comment]
Happy to hear it's working now. Thank you for letting me know!
