### ISSUE TITLE
Installing FTPClient fails

### ISSUE THREAD

**Issue by AlfonsNiederhofer** [fman-community/fman#712]
Hi,

installing plugins worked out of the box so far for different plugins.
With FTPClient I got the error below. Does anyone know the reason for that issue?

Thanks, Alfons

`Plugin 'FTPClient' failed to load.

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 125, in load
  File "fman/impl/plugins/plugin.py", line 141, in _load
  File "fman/impl/plugins/plugin.py", line 164, in _load_classes
  File "fman/impl/plugins/plugin.py", line 229, in _load_packages
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alfons/.config/fman/Plugins/Third-party/FTPClient/ftpclient/__init__.py", line 6, in <module>
    from .listeners import FtpListener
  File "/home/alfons/.config/fman/Plugins/Third-party/FTPClient/ftpclient/listeners.py", line 4, in <module>
    from core.commands import _open_local_file
ImportError: cannot import name '_open_local_file`

**Comment by mherrmann** [comment]
This is an issue for the FTPClient plugin. Please open an issue on its issue tracker.
