### ISSUE TITLE
windows 10 installation throwing error every folder change

### ISSUE THREAD

**Issue by ghost** [fman-community/fman#728]
every directory change thorws an error.
I tried to reinstall fman, without any success. (Installation path was C:\Users\andre\AppData\Local\fman\)

Maybe because the C:\Users\andre\AppData\Local\fman\Versions\1.7.0 is still there after removal of the app

I tried a second install with deleting the folder inbeween.
No success

The details of one error message 

-----

DirectoryPaneListener 'GoToListener' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 311, in _notify_listener_in_thread
  File "C:\Users\andre\AppData\Local\fman\Versions\1.7.0\Plugins\Core\core\commands\goto.py", line 148, in on_path_changed
    load_json('Visited Paths.json', default={}, save_on_quit=True)
  File "fman\__init__.py", line 213, in load_json
  File "fman\impl\plugins\__init__.py", line 37, in load_json
  File "fman\impl\plugins\config.py", line 27, in load_json
  File "fman\impl\plugins\config.py", line 91, in load_json
  File "json\__init__.py", line 299, in load
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

-----

**Comment by ghost** [comment]
by the way - I am using a payed fman

**Comment by ghost** [comment]
one further inspection showed that my Visited Paths (Windows).json in C:\Users\andre\AppData\Roaming\fman\Plugins\User\Settings was corrupted with content of NULL data

replacing that content with a simple object/dictionary seems to solve it

**Comment by mherrmann** [comment]
Happy you got it working again! And thank you for letting me know.

**Comment by RiccSicc** [comment]
I had the same problem on Windows 11.

I resolved this way:
1. uninstalled fman;
2. manually delete of folder c:\Users\{$ myUser}\AppData\Local\fman
3. manually delete of folder c:\Users\{$ myUser}\AppData\Roaming\fman
4. reinstalled fman.
