### ISSUE TITLE
Python backtrace when opening a .tf file

### ISSUE THREAD

**Issue by dragz** [fman-community/fman#738]
I'm getting this backtrace when I try to open a terraform file .tf. This is on Win10. It should open VS Code as it does for other files, like .py files. The installation is bog standard, just installed fman.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 128, in _execute_command
  File "C:\Users\roy000\AppData\Local\fman\Versions\1.7.2\Plugins\Core\core\commands\__init__.py", line 294, in __call__
    _open_files([url], self.pane)
  File "C:\Users\roy000\AppData\Local\fman\Versions\1.7.2\Plugins\Core\core\commands\__init__.py", line 327, in _open_files
    _open_local_files(local_file_paths, pane)
  File "C:\Users\roy000\AppData\Local\fman\Versions\1.7.2\Plugins\Core\core\commands\__init__.py", line 331, in _open_local_files
    _open_local_files_win(paths, pane)
  File "C:\Users\roy000\AppData\Local\fman\Versions\1.7.2\Plugins\Core\core\commands\__init__.py", line 362, in _open_local_files_win
    ShellExecute(0, None, path, None, cwd, SW_SHOWNORMAL)
pywintypes.error: (31, 'ShellExecute', 'A device attached to the system is not functioning.')

![image](https://user-images.githubusercontent.com/2721495/78280477-770a0900-7519-11ea-92e1-988d6d833714.png)

**Comment by mherrmann** [comment]
Does it persist across computer restarts?

**Comment by dragz** [comment]
Yes. I tested it right now.

**Comment by dragz** [comment]
The same happens if I try to open a .toml file. (toml files are configs for cargo, the package manager for the rust language)

**Comment by mherrmann** [comment]
And it works when you open the files from Explorer?

**Comment by dragz** [comment]
Yes, Explorer asks me for which application I wants to use to open the file. If I associate the file with an application in Explorer (right-click -> Properties) the problem goes away.
