### ISSUE TITLE
Problem with "Open With" Command

### ISSUE THREAD

**Issue by griloHBG** [fman-community/fman#749]
Hi! 

I'm trying new file explorers and fman is very interesting!

My current problem is the following.

With a PDF file selected, I choosed the "Open With" command.
Then that little window asking for the application appeared.
I typed foxit only to test what would happen.
A error raised, but this was expected, as foxit is not a valid command.
Then, over the same PDF file, I choosed "Open With" again.
From this time on, I always get this error:

![image](https://user-images.githubusercontent.com/13663866/81828551-494cb280-9510-11ea-9167-9f410662810c.png)

Text of the image:

```
Command 'OpenWith' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 128, in _execute_command
  File "C:\Users\Grilo\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1862, in __call__
    ShowAppsForOpening(files).show()
  File "C:\Users\Grilo\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1956, in show
    choice = show_quicksearch(lambda q: self._filter_options(options, q))
  File "fman\__init__.py", line 235, in show_quicksearch
  File "fman\impl\util\qt\thread.py", line 11, in result
  File "fman\impl\util\qt\thread.py", line 81, in run_in_thread
  File "fman\impl\util\qt\thread.py", line 106, in result
  File "fman\impl\util\qt\thread.py", line 94, in __call__
  File "fman\impl\widgets.py", line 368, in show_quicksearch
  File "fman\impl\util\qt\thread.py", line 11, in result
  File "fman\impl\util\qt\thread.py", line 66, in run_in_thread
  File "fman\impl\widgets.py", line 383, in exec_dialog
  File "fman\impl\quicksearch.py", line 35, in exec
  File "fman\impl\quicksearch.py", line 108, in _update_items
  File "C:\Users\Grilo\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1972, in _filter_options
    match = matcher(option.lower(), query.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
```

This will happen with any PDF file that I try to execute "Open With" command.

How can I resolve it?

Thanks in advance

**Comment by mherrmann** [comment]
You may have to delete one of the settings files in your data directory. (Google fman data directory.)

**Comment by griloHBG** [comment]
That's it!

Found this: [https://fman.io/docs/data-directory](https://fman.io/docs/data-directory)

There was a ```".pdf": {"null": 1}``` in the ```File Associations (Windows).json```.

Deleting that part of the file was enough.

Thank you!
