### ISSUE TITLE
DirectoryPaneListener 'RememberSortSettings' raised error.

### ISSUE THREAD

**Issue by zyryanov** [fman-community/fman#755]
After Windows has crashed, each time I change directory, I get the following exception:
```
DirectoryPaneListener 'RememberSortSettings' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 301, in before_location_change
  File "C:\Users\*\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1795, in before_location_change
    self._remember_curr_sort_column()
  File "C:\Users\*\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1816, in _remember_curr_sort_column
    settings = load_json('Sort Settings.json', default={})
  File "fman\__init__.py", line 213, in load_json
  File "fman\impl\plugins\__init__.py", line 37, in load_json
  File "fman\impl\plugins\config.py", line 27, in load_json
  File "fman\impl\plugins\config.py", line 91, in load_json
  File "json\__init__.py", line 299, in load
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

It was caused by `Sort Settings (Windows).json` file's content being only `\0\0`. The issue disappeared after the file was removed.

**Comment by mherrmann** [comment]
Thank you for sharing your solution!
