### ISSUE TITLE
Doesn't run on ubuntu 20.04

### ISSUE THREAD

**Issue by costa100** [fman-community/fman#761]
Hello, I just installed fman on ubuntu 20.04 and when I start the app nothing happens. I followed the instructions from the page: https://fman.io/download/thank-you?os=Linux&distribution=Ubuntu.

I don't have time look deeper into it, sorry. I use the default desktop which gnome based.

Thanks

**Comment by mherrmann** [comment]
What do you get when you type `/opt/fman/fman` into the terminal?

**Comment by costa100** [comment]
I get this:


Traceback (most recent call last):
  File "fman/main.py", line 21, in <module>
  File "fman/main.py", line 4, in main
  File "/root/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "fman/__init__.py", line 1, in <module>
  File "/root/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "fman/clipboard.py", line 4, in <module>
  File "/root/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "fman/impl/util/qt/thread.py", line 3, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[3980] Failed to execute script main

**Comment by costa100** [comment]
Just to clarify, I have ubuntu 20.04 desktop.

**Comment by costa100** [comment]
I have libffi7 installed.

 sudo apt-get install libffi7
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi7 is already the newest version (3.3-4).
libffi7 set to manually installed.
The following package was automatically installed and is no longer required:
  libllvm9

**Comment by costa100** [comment]
ok, I found this: https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6

I executed this command: `sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6`

but now I get this:

Traceback (most recent call last):
  File "fman/main.py", line 21, in <module>
  File "fman/main.py", line 4, in main
  File "/root/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "fman/__init__.py", line 1, in <module>
  File "/root/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "fman/clipboard.py", line 4, in <module>
  File "/root/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "fman/impl/util/qt/thread.py", line 3, in <module>
ImportError: /lib/x86_64-linux-gnu/libGL.so.1: undefined symbol: g_PrlGBMApi
[11620] Failed to execute script main

Just to give more details, my ubuntu vm runs inside desktop parallels on a MackookPro 2014 - I have the NVIDIA card.

**Comment by costa100** [comment]
Now, I found this: https://github.com/Qv2ray/Qv2ray/issues/367

It may be an issue with the NVIDIA parallels desktop driver. 

It is, I disabled the 3d acceleration and fman now works.

Wow, that was quite a ride.

**Comment by mherrmann** [comment]
Glad you got it to work!
