### ISSUE TITLE
Pack command throws an errror

### ISSUE THREAD

**Issue by svlcode** [fman-community/fman#774]
Hi there. 
I'm using Win10.
When trying to use the pack command to zip a folder I'm getting this error:

Command 'Pack' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 128, in _execute_command
  File "C:\Users\viore\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1699, in __call__
    submit_task(_Pack(files, dest_rewritten))
  File "fman\__init__.py", line 323, in submit_task
  File "C:\Users\viore\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1712, in __call__
    self.run(task)
  File "fman\__init__.py", line 309, in run
  File "C:\Users\viore\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\fs\zip.py", line 321, in __call__
    self._zip_fs.notify_file_added(dest_path)
  File "tempfile.py", line 809, in __exit__
  File "tempfile.py", line 813, in cleanup
  File "shutil.py", line 494, in rmtree
  File "shutil.py", line 384, in _rmtree_unsafe
  File "shutil.py", line 389, in _rmtree_unsafe
  File "shutil.py", line 387, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\viore\\AppData\\Local\\Temp\\tmpih9ilc4s\\.NET Internals and Advanced Debugging Techniques\\0 Introduction and Overview 20111221191129.mp4'

Can you please take a look?
If more info is needed please ask.
Thx!

**Comment by 5472qaywsx** [comment]
Hi @svlcode, I can't actually reproduce this... are you sure that you have access to that directory `C:\Users\viore\AppData\Local\Temp\tmpih9ilc4s\.NET Internals and Advanced Debugging Techniques\`?
Actually, it seems that you set an existing *file* (`0 Introduction and Overview 20111221191129.mp4`) as destination *directory*? Maybe `fman` interprets it's a directory if it has an extension other than expected for this function (.zip, .7z, .tar)?
(Other things I can think of: length of path (142 characters), character "`.`" in the path, but this should be answered by the developer if it could be a problem.)
