### ISSUE TITLE
Path Length

### ISSUE THREAD

**Issue by Warburgia** [fman-community/fman#780]
What are the file/folder path length restrictions using fman? I assume none for Linux, but Mac Finder has a 1024 byte limit, although the file system and OS do not. How about Windows 10 ? Many versions of Windows have a total path length restriction of 255 characters, although NTFS has a restriction of 32,767 characters. Many thanks if you can advise.

**Comment by mherrmann** [comment]
I don't know off the top of my head. Why don't you just try it? fman is free to evaluate.

**Comment by Warburgia** [comment]
Okay I will try, but please let me know if you have any thoughts on the matter. I have created a cascading (recursive) folder structure for my family tree which is okay in Linux as there are few if any path length restrictions, but want to know how it can be made to work in Mac/Windows (both can read the same if on a CD or iso file, for example)

**Comment by Warburgia** [comment]
Ok. I probably should have mentioned that in the process I created a new copyrighted genealogical numbering system, and am writing a book, in which I plan to mention under which file browsers it is possible (by path length) to create such trees (really a flat digital family history information archive), or not.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Warburgia** [comment]
I think the answer is no, at least in Windows 10. I get the following error code trying to copy across a deeply nested folder structure from an ext4 partition to a test folder on Drive C (NTFS):

Version:1.0 StartHTML:0000000107 EndHTML:0000007228 StartFragment:0000000538 EndFragment:0000007192

Command 'Copy' raised error.

Traceback (most recent call last):

File "fman\impl\fs_cache.py", line 36, in query

KeyError: 'stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "fman\impl\plugins\command_registry.py", line 128, in _execute_command

File "C:\Users\auser\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 551, in __call__

self._call(files, dest_dir, dest_name)

File "C:\Users\auser\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 705, in _call

submit_task(CopyFiles(files, dest_dir, dest_name))

File "fman\__init__.py", line 323, in submit_task

File "C:\Users\auser\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\fileoperations.py", line 41, in __call__

if not self._gather_files():

File "C:\Users\auser\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\fileoperations.py", line 91, in _gather_files

self._enqueue(self._prepare_transfer(src, dest))

File "C:\Users\auser\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\fileoperations.py", line 156, in _enqueue

for task in self._iter(tasks):

File "C:\Users\auser\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\fileoperations.py", line 216, in _iter

for item in iterable:

File "C:\Users\auser\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\fs\local\__init__.py", line 266, in _prepare_copy

join(src_url, name), join(dst_url, name), measure_size

File "C:\Users\auser\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\fs\local\__init__.py", line 266, in _prepare_copy

join(src_url, name), join(dst_url, name), measure_size

File "C:\Users\auser\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\fs\local\__init__.py", line 258, in _prepare_copy

src_is_dir = self.is_dir(src_path)

File "C:\Users\auser\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\fs\local\__init__.py", line 46, in is_dir

return S_ISDIR(self.stat(existing_path).st_mode)

File "fman\fs.py", line 199, in wrapper

File "fman\impl\fs_cache.py", line 12, in query

File "fman\impl\fs_cache.py", line 38, in query

File "fman\fs.py", line 199, in <lambda>

I couldn't copy the whole thing, as it would not scroll down

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
