### ISSUE TITLE
ValueError: Path must be absolute

### ISSUE THREAD

**Issue by ymyke** [fman-community/fman#793]
I'm simply trying to copy files from one directory to another an get the following:

```
Command 'Copy' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 128, in _execute_command
  File "C:\Users\myken\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 550, in __call__
    makedirs(dest_dir, exist_ok=True)
  File "fman\fs.py", line 19, in makedirs
  File "fman\impl\plugins\mother_fs.py", line 75, in makedirs
  File "fman\fs.py", line 118, in makedirs
  File "C:\Users\myken\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\fs\local\__init__.py", line 73, in mkdir
    raise ValueError('Path must be absolute')
ValueError: Path must be absolute
```

* Windows 10
* fman 1.7.3

Any idea what is happening here?

**Comment by mherrmann** [comment]
I can't reproduce the problem. What exactly did you do? Did you press F5? Was it one files, or multiple? Did you enter anything into the dialog that opens when you press F5? ...

**Comment by ymyke** [comment]
* Not F5, I selected Copy via ctrl-shift-p
* 9 files
* I didn't enter anything

I'm not surprised that you cannot reproduce the problem. Otherwise many others must have reported this problem. 

I restarted fman in the meantime and it seems to be working now...
