### ISSUE TITLE
fman doesn't work on CentOS 8 (libssl.so.10: cannot open shared object file)

### ISSUE THREAD

**Issue by mluethi** [fman-community/fman#797]
Hi!

I installed fman (fman.x86_64, 1.7.3-1) from repository (as per instructions on fman.io website) on CentOS 8.3.2011 and got:

    Traceback (most recent call last):
      File "fman/main.py", line 21, in <module>
      File "fman/main.py", line 4, in main
      File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
      File "fman/impl/application_context.py", line 11, in <module>
      File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
      File "fman/impl/metrics.py", line 7, in <module>
      File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
      File "ssl.py", line 101, in <module>
    ImportError: libssl.so.10: cannot open shared object file: No such file or directory
    [34290] Failed to execute script main

Seeing **fman doesn't work on Fedora 30 #654** I tried:

    sudo yum install compat-openssl10.x86_64

This resolved the issue.
Maybe you can adjust the installation. ;-)

**Comment by mherrmann** [comment]
Thank you! I've update the installation instructions.

![image](https://user-images.githubusercontent.com/1076393/103502937-1f575000-4e53-11eb-9be2-b1e77552fcaa.png)
