### ISSUE TITLE
LookupError: unknown encoding: idna when trying to install plugin

### ISSUE THREAD

**Issue by domelqq** [fman-community/fman#814]
Hi when trying to install plugin 
Command 'InstallPlugin' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 66, in _execute_command
  File "C:\Users\domagalm\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1393, in __call__
    self._plugin_repos = \
  File "C:\Users\domagalm\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\github.py", line 13, in find_repos
    return list(map(GitHubRepo, _fetch_all_pages(url)))
  File "C:\Users\domagalm\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\github.py", line 17, in _fetch_all_pages
    data = _get_json(json_url + '&per_page=%d&page=%d' % (page_size, page))
  File "C:\Users\domagalm\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\github.py", line 72, in _get_json
    return json.loads(_get(url).decode('utf-8'))
  File "C:\Users\domagalm\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\github.py", line 76, in _get
    return urlopen(url).read()
  File "urllib\request.py", line 223, in urlopen
  File "urllib\request.py", line 526, in open
  File "urllib\request.py", line 544, in _open
  File "urllib\request.py", line 504, in _call_chain
  File "urllib\request.py", line 1361, in https_open
  File "urllib\request.py", line 1318, in do_open
  File "http\client.py", line 1239, in request
  File "http\client.py", line 1285, in _send_request
  File "http\client.py", line 1234, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 964, in send
  File "http\client.py", line 1392, in connect
  File "http\client.py", line 936, in connect
  File "socket.py", line 704, in create_connection
  File "socket.py", line 745, in getaddrinfo
LookupError: unknown encoding: idna

**Comment by domelqq** [comment]
Somehow this issue gone by itself. I would say ic can be closed.
