### ISSUE TITLE
[Windows] PermissionError WinError5

### ISSUE THREAD

**Issue by questor** [fman-community/fman#818]
Hi,
I just installed fman to test it, but can't really use it because on every directory-change it tries to write a json settings file which is not possible on my machine for whatever reason.

DirectoryPaneListener 'RememberSortSettings' raised error.
Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 301, in before_location_change
  File "C:\Users\...\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1795, in before_location_change
    self._remember_curr_sort_column()
  File "C:\Users\...\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1825, in _remember_curr_sort_column
    save_json('Sort Settings.json')
  File "fman\__init__.py", line 216, in save_json
  File "fman\impl\plugins\__init__.py", line 39, in save_json
  File "fman\impl\plugins\config.py", line 40, in save_json
  File "fman\impl\plugins\config.py", line 120, in write_differential_json
PermissionError: [WinError 5] Zugriff verweigert: 'C:\\Users\\...\\AppData\\Roaming\\fman\\Plugins\\User\\Settings\\Sort Settings (Windows).json.tmp10944' -> 'C:\\Users\\...\\AppData\\Roaming\\fman\\Plugins\\User\\Settings\\Sort Settings (Windows).json'

I've found that the whole fman-folder is always set to read-only, not sure if that is the issue or who is doing it. 

Any idea what is going on?!

**Comment by questor** [comment]
starting fman one time as admin, closing it and running again as normal user fixed it....

**Comment by mherrmann** [comment]
Happy to hear it. Thank you for sharing your experiences.
