### ISSUE TITLE
fman doesn't start

### ISSUE THREAD

**Issue by edewit** [fman-community/fman#848]
os: Fedora 35 compat-openssl10 installed

```bash
/opt/fman/fman
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 149, in __init__
  File "ctypes/__init__.py", line 343, in __init__
OSError: /lib64/libgio-2.0.so.0: undefined symbol: g_module_open_full

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fman/main.py", line 21, in <module>
  File "fman/main.py", line 6, in main
  File "fman/impl/application_context.py", line 62, in run
  File "fman/impl/application_context.py", line 84, in _load_plugins
  File "fman/impl/application_context.py", line 143, in main_window
  File "fman/impl/application_context.py", line 201, in mother_fs
  File "fman/impl/application_context.py", line 205, in _get_icon_provider
  File "fman/impl/model/icon_provider.py", line 52, in __init__
  File "fman/impl/model/icon_provider.py", line 63, in _init_pgi
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "pgi/__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "pgi/importer.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "pgi/clib/gir/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "pgi/clib/gir/gibaseinfo.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "pgi/clib/gir/gitypelib.py", line 16, in <module>
  File "pgi/clib/_utils.py", line 99, in find_library
  File "ctypes/__init__.py", line 421, in LoadLibrary
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 151, in __init__
PyInstallerImportError: Failed to load dynlib/dll 'libgirepository-1.0.so.1'. Most probably this dynlib/dll was not found when the application was frozen.
[19163] Failed to execute script main
```

**Comment by mherrmann** [comment]
This is a duplicate of #842. Can you find a way to install `libgirepository` on your system?

**Comment by edewit** [comment]
I think the problem is that I have version 2.0 but fman is compiled against 1.0:

```bash
$> ll /lib64/libgmodul*
lrwxrwxrwx. 1 root root  26 Mar 18 10:51 /lib64/libgmodule-2.0.so.0 -> libgmodule-2.0.so.0.7000.5
-rwxr-xr-x. 1 root root 24K Mar 18 10:54 /lib64/libgmodule-2.0.so.0.7000.5
```
resulting in this error: `OSError: /lib64/libgio-2.0.so.0: undefined symbol: g_module_open_full`
