### ISSUE TITLE
Command 'OpenWith' raised error - FIX

### ISSUE THREAD

**Issue by SpeedySparrow** [fman-community/fman#865]
Suddenly I got this error when trying to use the Open with ... functionality. Apparently my C:\Users\USER\AppData\Roaming\fman\Plugins\User\Settings\File Associations (Windows).json had gotten corrupted. The format of this file is:
{".py": {"VSCode": 1}}
Adding this line to File Associations (Windows).json fixed my problem. The application name is found in Apps (Windows).json. 

Command 'OpenWith' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 128, in _execute_command
  File "C:\Users\USER\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1862, in __call__
    ShowAppsForOpening(files).show()
  File "C:\Users\USER\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1955, in show
    options = list(self.get_options())
  File "C:\Users\USER\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1987, in get_options
    _load_file_associations().items(),
  File "C:\Users\USER\AppData\Local\fman\Versions\1.7.3\Plugins\Core\core\commands\__init__.py", line 1908, in _load_file_associations
    return load_json('File Associations.json', {})
  File "fman\__init__.py", line 213, in load_json
  File "fman\impl\plugins\__init__.py", line 37, in load_json
  File "fman\impl\plugins\config.py", line 27, in load_json
  File "fman\impl\plugins\config.py", line 91, in load_json
  File "json\__init__.py", line 299, in load
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by SpeedySparrow** [comment]
Issue has been fixed and explanation added to the issue.
