### ISSUE TITLE
Error when launching fman on Fedora 38

### ISSUE THREAD

**Issue by frr149** [fman-community/fman#874]
When I try to launch fman (via the script in `usr/bin/` , nothing happens I get no feedback. 

If I try to launch the binary in `/opt/fman/fman/` ,  I get the following error message:

```
/opt/fman ᐅ ./fman
Traceback (most recent call last):
  File "fman/main.py", line 21, in <module>
  File "fman/main.py", line 4, in main
  File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "fman/impl/application_context.py", line 11, in <module>
  File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "fman/impl/metrics.py", line 7, in <module>
  File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "ssl.py", line 101, in <module>
ImportError: libssl.so.10: cannot open shared object file: No such file or directory
[82751] Failed to execute script main
```

I'm on Fedora 38, BTW.

```
OS: Fedora Linux 38 (Workstation Edition) x86_64 
Host: PROX15 Standard 
Kernel: 6.2.12-300.fc38.x86_64 
Uptime: 7 hours, 58 mins 
Packages: 2497 (rpm), 63 (flatpak), 20 (snap) 
Shell: zsh 5.9 
Resolution: 1920x1080, 2560x1440 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-9750H (12) @ 4.500GHz 
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
Memory: 11385MiB / 31937MiB 
```

**Comment by fhenneke** [comment]
I have the same issue on Fedora 40.

The install instruction `dnf install compat-openssl10` does not work.
